
on: 
  schedule:
  - cron: '*/2 * * * *'


jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Update submodules
        run: |
        git submodule update --remote --merge
        git add -u
        git commit -m "cron: Updated submodules"
        git push