name: Update Docs
on: 
  schedule:
  - cron: '*/10 * * * *'


jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Update submodules
        run: |
          git submodule update --remote --merge