name: Manually triggered workflow
on:
  workflow_dispatch:

jobs:
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Update submodules
        run: |
          git submodule update --remote --merge
          git add -u
          git commit -m "Update submodules"
          git push